<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTk5hyy5\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTk5hyy5/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerTk5hyy5.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerTk5hyy5\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerTk5hyy5\appProdProjectContainer([
    'container.build_hash' => 'Tk5hyy5',
    'container.build_id' => '75314f28',
    'container.build_time' => 1666393070,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTk5hyy5');
